# Generated by Django 3.2.23 on 2023-12-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_like_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='user',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
